Repository tgstation/tgstation-server, pull requests merged in 2018-07, with the labels that each got.

#528 Save configuration after modification
  TGS.Server/InstanceConfig.cs
Labels: Review

#533 Revert "Save configuration after modification"
  TGS.Server/InstanceConfig.cs
Labels: Revert, Review

#534 Brute force config saving
  TGS.Server/Instance/Chat.cs
  TGS.Server/Instance/Compiler.cs
  TGS.Server/Instance/DreamDaemon.cs
  TGS.Server/Instance/Repository.cs
  TGS.Server/InstanceConfig.cs
Labels: Fix, Review

#538 Fixes being unable to refresh active instances
  TGS.ControlPanel/InstanceSelector.cs
  TGS.Interface/IServer.cs
  TGS.Interface/Server.cs
Labels: Fix, Review

#536 Changed background color to lighter gray
  TGS.ControlPanel/ControlPanel/ControlPanel.Designer.cs
Labels: Review

#540 Revert "Changed background color to lighter gray"
  TGS.ControlPanel/ControlPanel/ControlPanel.Designer.cs
Labels: Review

#542 Adds more watchdog logs
  TGS.Server/EventID.cs
  TGS.Server/Instance/DreamDaemon.cs
Labels: Review

#539 Continued v4 work
  UpgradeLog.htm
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/v4/api.dm
  src/DMAPI/tgs/v4/commands.dm
  src/Tgstation.Server.Api/Models/ChatChannel.cs
  src/Tgstation.Server.Api/Models/ChatProvider.cs
  src/Tgstation.Server.Api/Models/ChatSettings.cs
  src/Tgstation.Server.Api/Models/Internal/ChatSettings.cs
  src/Tgstation.Server.Api/Rights/ChatSettingsRights.cs
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host/Components/Chat/Channel.cs
  src/Tgstation.Server.Host/Components/Chat/ChannelMapping.cs
  src/Tgstation.Server.Host/Components/Chat/Chat.cs
  src/Tgstation.Server.Host/Components/Chat/ChatResponse.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/Command.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/CustomCommand.cs
  src/Tgstation.Server.Host/Components/Chat/IChat.cs
  src/Tgstation.Server.Host/Components/Chat/IChatJsonTrackingContext.cs
  src/Tgstation.Server.Host/Components/Chat/ICommandFactory.cs
  src/Tgstation.Server.Host/Components/Chat/ICustomCommandHandler.cs
  src/Tgstation.Server.Host/Components/Chat/IJsonTrackingContext.cs
  src/Tgstation.Server.Host/Components/Chat/IProviderFactory.cs
  src/Tgstation.Server.Host/Components/Chat/JsonTrackingContext.cs
  src/Tgstation.Server.Host/Components/Chat/Message.cs
  src/Tgstation.Server.Host/Components/Chat/ProviderFactory.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Response.cs
  src/Tgstation.Server.Host/Components/Chat/User.cs
  src/Tgstation.Server.Host/Components/DreamMaker.cs
  src/Tgstation.Server.Host/Components/EventType.cs
  src/Tgstation.Server.Host/Components/Watchdog/ISessionController.cs
  src/Tgstation.Server.Host/Components/Watchdog/ISessionControllerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/SessionController.cs
  src/Tgstation.Server.Host/Components/Watchdog/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogFactory.cs
  src/Tgstation.Server.Host/Controllers/ChatController.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Controllers/DreamMakerController.cs
  src/Tgstation.Server.Host/Controllers/InstanceController.cs
  src/Tgstation.Server.Host/Controllers/JobController.cs
  src/Tgstation.Server.Host/Models/ChatChannel.cs
  src/Tgstation.Server.Host/Models/ChatSettings.cs
  src/Tgstation.Server.Host/Models/DatabaseContext.cs
  src/Tgstation.Server.Host/Models/IDatabaseContext.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Review

#543 Remove static reset from repo recloning
  TGS.Server/Instance/Repository.cs
Labels: Review

#547 Removes DD check from repo recloning
  TGS.Server/Instance/Repository.cs
Labels: Removal, Review

#548 Create releases as drafts until I stop being lazy and add auto release notes
  appveyor.yml
Labels: Review

#545 Implement the chat subsystem
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/v4/api.dm
  src/Tgstation.Server.Api/Models/ChatChannel.cs
  src/Tgstation.Server.Api/Models/CompileJob.cs
  src/Tgstation.Server.Api/Models/Internal/CompileJob.cs
  src/Tgstation.Server.Host/Components/Chat/Channel.cs
  src/Tgstation.Server.Host/Components/Chat/ChannelMapping.cs
  src/Tgstation.Server.Host/Components/Chat/Chat.cs
  src/Tgstation.Server.Host/Components/Chat/ChatFactory.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/BoolConverter.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/Command.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/CommandFactory.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/CustomCommand.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/ICommand.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/ICommandFactory.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/KekCommand.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/VersionCommand.cs
  src/Tgstation.Server.Host/Components/Chat/IChat.cs
  src/Tgstation.Server.Host/Components/Chat/IChatFactory.cs
  src/Tgstation.Server.Host/Components/Chat/ICommandFactory.cs
  src/Tgstation.Server.Host/Components/Chat/ICustomCommandHandler.cs
  src/Tgstation.Server.Host/Components/Chat/Message.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcPasswordType.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/Provider.cs
  src/Tgstation.Server.Host/Components/Chat/Response.cs
  src/Tgstation.Server.Host/Components/Chat/User.cs
  src/Tgstation.Server.Host/Components/DreamMaker.cs
  src/Tgstation.Server.Host/Components/EventType.cs
  src/Tgstation.Server.Host/Components/IEventConsumer.cs
  src/Tgstation.Server.Host/Components/IInstance.cs
  src/Tgstation.Server.Host/Components/IInstanceFactory.cs
  src/Tgstation.Server.Host/Components/Instance.cs
  src/Tgstation.Server.Host/Components/InstanceFactory.cs
  src/Tgstation.Server.Host/Components/InstanceManager.cs
  src/Tgstation.Server.Host/Components/ReattachInfoHandler.cs
  src/Tgstation.Server.Host/Components/Watchdog/IWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Core/IApplication.cs
  src/Tgstation.Server.Host/Models/CompileJob.cs
  src/Tgstation.Server.Host/Models/DatabaseContext.cs
  tests/Tgstation.Server.Host.Tests/Core/TestApplication.cs
Labels: Review

#544 Watchdog event handlers
  src/Tgstation.Server.Host/Components/Watchdog/ISessionController.cs
  src/Tgstation.Server.Host/Components/Watchdog/MonitorAction.cs
  src/Tgstation.Server.Host/Components/Watchdog/MonitorActivationReason.cs
  src/Tgstation.Server.Host/Components/Watchdog/MonitorState.cs
  src/Tgstation.Server.Host/Components/Watchdog/SessionController.cs
  src/Tgstation.Server.Host/Components/Watchdog/Watchdog.cs
Labels: Review

#553 Adds IRC nick correcting
  TGS.Server/ChatProviders/IRCChatProvider.cs
Labels: Review
