Repository tgstation/tgstation-server, pull requests merged in 2018-06, with the labels that each got.

#519 Moves the TLS 1.2 meme to global startup
  TGS.Server/Instance/Repository.cs
  TGS.Server/Server.cs
Labels: Fix, Review

#520 Auto install included DX redis if upgrading to a byond version >= 512.1427
  TGS.Server/Instance/Byond.cs
Labels: Feature, Fix, Review

#527 Remove docker-compose
  docker-compose.dcproj
  docker-compose.yml
  tgstation-server.sln
Labels: Review

#526 Simple command line registration for the service, everything else is manual
  src/Tgstation.Server.Host.Service/Program.cs
  src/Tgstation.Server.Host.Service/ServerService.cs
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
Labels: Review

#518 Some watchdog stuff I forgot to merge then went looking for
  appveyor.yml
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonLaunchParameters.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonSettings.cs
  src/Tgstation.Server.Host/Components/DreamDaemon.cs
  src/Tgstation.Server.Host/Components/DreamDaemonExecutor.cs
  src/Tgstation.Server.Host/Components/DreamMaker.cs
  src/Tgstation.Server.Host/Components/IDmbProvider.cs
  src/Tgstation.Server.Host/Components/IDreamDaemon.cs
  src/Tgstation.Server.Host/Components/IDreamDaemonExecutor.cs
  src/Tgstation.Server.Host/Components/IInteropControl.cs
  src/Tgstation.Server.Host/Components/IWatchdog.cs
  src/Tgstation.Server.Host/Components/TemporaryDmbProvider.cs
  src/Tgstation.Server.Host/Components/Watchdog.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Controllers/DreamMakerController.cs
  src/Tgstation.Server.Host/Controllers/JobController.cs
  src/Tgstation.Server.Host/Controllers/ModelController.cs
Labels: Review

#529 Revert "Some watchdog stuff I forgot to merge then went looking for"
  appveyor.yml
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonLaunchParameters.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonSettings.cs
  src/Tgstation.Server.Host/Components/DreamDaemon.cs
  src/Tgstation.Server.Host/Components/DreamDaemonExecutor.cs
  src/Tgstation.Server.Host/Components/DreamMaker.cs
  src/Tgstation.Server.Host/Components/IDmbProvider.cs
  src/Tgstation.Server.Host/Components/IDreamDaemon.cs
  src/Tgstation.Server.Host/Components/IDreamDaemonExecutor.cs
  src/Tgstation.Server.Host/Components/IInteropControl.cs
  src/Tgstation.Server.Host/Components/IWatchdog.cs
  src/Tgstation.Server.Host/Components/TemporaryDmbProvider.cs
  src/Tgstation.Server.Host/Components/Watchdog.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Controllers/DreamMakerController.cs
  src/Tgstation.Server.Host/Controllers/JobController.cs
  src/Tgstation.Server.Host/Controllers/ModelController.cs
Labels: Revert, Review

#530 Revert "Revert "Some watchdog stuff I forgot to merge then went looking for""
  appveyor.yml
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonLaunchParameters.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonSettings.cs
  src/Tgstation.Server.Host/Components/DreamDaemon.cs
  src/Tgstation.Server.Host/Components/DreamDaemonExecutor.cs
  src/Tgstation.Server.Host/Components/DreamMaker.cs
  src/Tgstation.Server.Host/Components/IDmbProvider.cs
  src/Tgstation.Server.Host/Components/IDreamDaemon.cs
  src/Tgstation.Server.Host/Components/IDreamDaemonExecutor.cs
  src/Tgstation.Server.Host/Components/IInteropControl.cs
  src/Tgstation.Server.Host/Components/IWatchdog.cs
  src/Tgstation.Server.Host/Components/TemporaryDmbProvider.cs
  src/Tgstation.Server.Host/Components/Watchdog.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Controllers/DreamMakerController.cs
  src/Tgstation.Server.Host/Controllers/JobController.cs
  src/Tgstation.Server.Host/Controllers/ModelController.cs
Labels: Review
