Repository tgstation/tgstation-server, pull requests merged in 2018-02, with the labels that each got.

#480 I don't know what I'm doing but the internet said blindly putting this code in play will fix appveyor
  appveyor.yml
Labels: Review

#477 Fixes unrelated values getting reset when editing a value in the control panel
  TGS.ControlPanel/Login.cs
Labels: Fix, Review

#484 Updates octokit
  TGS.ControlPanel/TGS.ControlPanel.csproj
  TGS.ControlPanel/packages.config
Labels: Fix, Review

#486 Force TLS1.2 usage
  TGS.Interface/Client.cs
Labels: Review

#487 Fix TLS usage for PR JSON update FUCK
  TGS.Server/Instance/Repository.cs
Labels: Fix, Priority: High, Review
