Repository tgstation/tgstation-server, pull requests merged in 2020-08, with the labels that each got.

#1096 v4.4.3
  build/Version.props
  src/Tgstation.Server.Host/Components/Chat/ChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/IChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/Provider.cs
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Components/Instance.cs
  src/Tgstation.Server.Host/Components/Interop/Bridge/RuntimeInformation.cs
  src/Tgstation.Server.Host/Components/Interop/Topic/EventNotification.cs
  src/Tgstation.Server.Host/Components/Repository/IRepository.cs
  src/Tgstation.Server.Host/Components/Repository/Repository.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
  src/Tgstation.Server.Host/Controllers/AdministrationController.cs
  src/Tgstation.Server.Host/Controllers/InstanceRequiredController.cs
  src/Tgstation.Server.Host/Controllers/RepositoryController.cs
  src/Tgstation.Server.Host/Core/Application.cs
  tests/Tgstation.Server.Tests/Instance/WatchdogTest.cs
  tests/Tgstation.Server.Tests/IntegrationTest.cs
  tests/Tgstation.Server.Tests/TestingServer.cs
Labels: Fix

#1099 v4.4.4
  build/Version.props
  src/Tgstation.Server.Api/Models/ErrorCode.cs
  src/Tgstation.Server.Host/Components/Byond/WindowsByondInstaller.cs
  src/Tgstation.Server.Host/Controllers/ConfigurationController.cs
Labels: API, Area: Byond, Fix

#1101 v4.4.5
  build/Version.props
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  src/Tgstation.Server.Host/Core/SwaggerConfiguration.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Fix, Release

#1100 improves grammar in README
  README.md
Labels: Documentation

#1105 Adds configuration option for swagger UI. Add DM Output display options to Discord embed. Add TokenFactory config settings. Plus other Discord buffs
  build/Version.props
  src/Tgstation.Server.Api/Models/DiscordConnectionStringBuilder.cs
  src/Tgstation.Server.Api/Models/DiscordDMOutputDisplayType.cs
  src/Tgstation.Server.Host/Components/Chat/ChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/Message.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  src/Tgstation.Server.Host/Components/Repository/LibGit2RepositoryFactory.cs
  src/Tgstation.Server.Host/Components/Repository/Repository.cs
  src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs
  src/Tgstation.Server.Host/Configuration/GeneralConfiguration.cs
  src/Tgstation.Server.Host/Configuration/SecurityConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/IO/Console.cs
  src/Tgstation.Server.Host/IO/DefaultIOManager.cs
  src/Tgstation.Server.Host/IO/PosixSymlinkFactory.cs
  src/Tgstation.Server.Host/IO/WindowsSymlinkFactory.cs
  src/Tgstation.Server.Host/Security/CryptographySuite.cs
  src/Tgstation.Server.Host/Security/TokenFactory.cs
  src/Tgstation.Server.Host/Security/WindowsSystemIdentity.cs
  src/Tgstation.Server.Host/Security/WindowsSystemIdentityFactory.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  src/Tgstation.Server.Host/System/AssemblyInformationProvider.cs
  src/Tgstation.Server.Host/System/IAssemblyInformationProvider.cs
  src/Tgstation.Server.Host/System/Process.cs
  src/Tgstation.Server.Host/System/WindowsProcessFeatures.cs
  src/Tgstation.Server.Host/appsettings.json
  tests/Tgstation.Server.Host.Tests/Setup/TestSetupWizard.cs
  tests/Tgstation.Server.Tests/Instance/ChatTest.cs
Labels: API, Area: Chat, Configuration, Feature, Security

#1111 Small patch
  README.md
  build/Version.props
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/v3210/api.dm
  src/DMAPI/tgs/v3210/commands.dm
  src/DMAPI/tgs/v5/api.dm
  src/Tgstation.Server.Api/Rights/AdministrationRights.cs
  src/Tgstation.Server.Api/Rights/ByondRights.cs
  src/Tgstation.Server.Api/Rights/ChatBotRights.cs
  src/Tgstation.Server.Api/Rights/ConfigurationRights.cs
  src/Tgstation.Server.Api/Rights/DreamDaemonRights.cs
  src/Tgstation.Server.Api/Rights/DreamMakerRights.cs
  src/Tgstation.Server.Api/Rights/InstanceManagerRights.cs
  src/Tgstation.Server.Api/Rights/InstanceUserRights.cs
  src/Tgstation.Server.Api/Rights/RepositoryRights.cs
  src/Tgstation.Server.Host/Components/Interop/DMApiConstants.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Database/DatabaseSeeder.cs
  src/Tgstation.Server.Host/Models/RepositorySettings.cs
Labels: Fix, Release
