Repository tgstation/tgstation-server, pull requests merged in 2020-01, with the labels that each got.

#879 Makes the existing watchdog experimental. Adds the basic watchdog
  src/Tgstation.Server.Host/Components/Instance.cs
  src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/ExperimentalWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/MonitorState.cs
  src/Tgstation.Server.Host/Components/Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogFactory.cs
  src/Tgstation.Server.Host/Configuration/GeneralConfiguration.cs
  src/Tgstation.Server.Host/appsettings.json
  tests/Tgstation.Server.Host.Tests/Components/Watchdog/TestExperimentalWatchdog.cs
Labels: Refactor

#882 Remove chocolatey cache from Appveyor build
  appveyor.yml
Labels: CI, Fix

#875 Adds parsing of port for MySQL/MariaDB databases in SetupWizard
  src/Tgstation.Server.Host/Core/SetupWizard.cs
Labels: Fix

#892 Deduplicate download code for IByondInstallers
  src/Tgstation.Server.Host/Components/Byond/ByondInstallerBase.cs
  src/Tgstation.Server.Host/Components/Byond/PosixByondInstaller.cs
  src/Tgstation.Server.Host/Components/Byond/WindowsByondInstaller.cs
  tests/Tgstation.Server.Host.Tests/Components/Byond/TestPosixByondInstaller.cs
Labels: Code Improvement

#893 Add Swagger/OpenAPI 3.0 generated specifications
  build/BuildDox.ps1
  docs/API.dox
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Api/Models/EntityId.cs
  src/Tgstation.Server.Api/Models/Internal/CompileJob.cs
  src/Tgstation.Server.Api/Models/Internal/Job.cs
  src/Tgstation.Server.Api/Rights/RightsHelper.cs
  src/Tgstation.Server.Api/Routes.cs
  src/Tgstation.Server.Client/ApiClient.cs
  src/Tgstation.Server.Client/Components/ByondClient.cs
  src/Tgstation.Server.Client/Components/ChatBotsClient.cs
  src/Tgstation.Server.Client/Components/ConfigurationClient.cs
  src/Tgstation.Server.Client/Components/DreamMakerClient.cs
  src/Tgstation.Server.Client/Components/IDreamMakerClient.cs
  src/Tgstation.Server.Client/Components/IJobsClient.cs
  src/Tgstation.Server.Client/Components/InstanceUserClient.cs
  src/Tgstation.Server.Client/Components/JobsClient.cs
  src/Tgstation.Server.Client/InstanceManagerClient.cs
  src/Tgstation.Server.Client/ServerErrorException.cs
  src/Tgstation.Server.Client/UsersClient.cs
  src/Tgstation.Server.Host/Controllers/AdministrationController.cs
  src/Tgstation.Server.Host/Controllers/ApiController.cs
  src/Tgstation.Server.Host/Controllers/ByondController.cs
  src/Tgstation.Server.Host/Controllers/ChatController.cs
  src/Tgstation.Server.Host/Controllers/ConfigurationController.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Controllers/DreamMakerController.cs
  src/Tgstation.Server.Host/Controllers/HomeController.cs
  src/Tgstation.Server.Host/Controllers/InstanceController.cs
  src/Tgstation.Server.Host/Controllers/InstanceUserController.cs
  src/Tgstation.Server.Host/Controllers/JobController.cs
  src/Tgstation.Server.Host/Controllers/ModelController.cs
  src/Tgstation.Server.Host/Controllers/RepositoryController.cs
  src/Tgstation.Server.Host/Controllers/TgsAuthorizeAttribute.cs
  src/Tgstation.Server.Host/Controllers/TgsOpenApiFilters.cs
  src/Tgstation.Server.Host/Controllers/UserController.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Core/ApplicationBuilderExtensions.cs
  src/Tgstation.Server.Host/Core/AssemblyInformationProvider.cs
  src/Tgstation.Server.Host/Core/IAssemblyInformationProvider.cs
  src/Tgstation.Server.Host/Core/JobManager.cs
  src/Tgstation.Server.Host/Core/SetupWizard.cs
  src/Tgstation.Server.Host/IO/Console.cs
  src/Tgstation.Server.Host/IO/IConsole.cs
  src/Tgstation.Server.Host/Models/CompileJob.cs
  src/Tgstation.Server.Host/Models/Migrations/DesignTimeDbContextFactoryHelpers.cs
  src/Tgstation.Server.Host/Program.cs
  src/Tgstation.Server.Host/Security/TokenFactory.cs
  src/Tgstation.Server.Host/Server.cs
  src/Tgstation.Server.Host/ServerFactory.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tests/Tgstation.Server.Host.Tests/Core/TestApplication.cs
  tests/Tgstation.Server.Host.Tests/TestServerFactory.cs
  tests/Tgstation.Server.Tests/IntegrationTest.cs
  tests/Tgstation.Server.Tests/TestingServer.cs
Labels: API, Documentation, Feature

#895 Fix installation directory instance detection.
  src/Tgstation.Server.Host/Controllers/InstanceController.cs
Labels: Fix, Review
