Repository tgstation/tgstation-server, pull requests merged in 2020-09, with the labels that each got.

#1116 Fix discordconnectionstringbuilder crash
  src/Tgstation.Server.Api/Models/DiscordConnectionStringBuilder.cs
Labels: API, Fix

#1115 Rearrange some code to detect a potential NullReferenceException
  src/Tgstation.Server.Host/Controllers/RepositoryController.cs
Labels: Code Improvement

#1120 v4.5.2
  .github/PULL_REQUEST_TEMPLATE.md
  build/Version.props
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/v3210/api.dm
  src/DMAPI/tgs/v3210/commands.dm
  src/DMAPI/tgs/v5/api.dm
  src/Tgstation.Server.Api/Rights/RightsHelper.cs
  src/Tgstation.Server.Host/Components/Interop/DMApiConstants.cs
  src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs
  src/Tgstation.Server.Host/Controllers/AdministrationController.cs
  src/Tgstation.Server.Host/Controllers/ApiController.cs
  src/Tgstation.Server.Host/Controllers/HomeController.cs
  src/Tgstation.Server.Host/Controllers/InstanceController.cs
  src/Tgstation.Server.Host/Controllers/InstanceRequiredController.cs
  src/Tgstation.Server.Host/Controllers/UserController.cs
  src/Tgstation.Server.Host/Core/SwaggerConfiguration.cs
Labels: Area: Static Files, Code Improvement, Documentation, Fix, GitHub, Release

#1122 v4.5.3
  build/Version.props
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
Labels: Fix, Release

#1125 v4.5.4
  build/Version.props
  src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
Labels: Fix, Release
