Repository tgstation/tgstation-server, pull requests merged in 2021-02, with the labels that each got.

#1218 Fixes trying to use empty github token in GithubClientFactory
  build/Version.props
  src/Tgstation.Server.Host/Core/GitHubClientFactory.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
Labels: Fix, Release

#1222 Fix PushTestMergeCommits not being respected
  src/Tgstation.Server.Host/Components/Events/EventType.cs
  src/Tgstation.Server.Host/Components/Instance.cs
  src/Tgstation.Server.Host/Components/Repository/Repository.cs
  src/Tgstation.Server.Host/Controllers/RepositoryController.cs
  src/Tgstation.Server.Host/Jobs/IJobManager.cs
Labels: Fix, Release

#1223 Better file copy
  src/Tgstation.Server.Host/IO/DefaultIOManager.cs
Labels: Performance

#1224 v4.9.2
  build/Version.props
  src/Tgstation.Server.Api/Models/Internal/SwarmServer.cs
  src/Tgstation.Server.Host/Components/Repository/Repository.cs
  src/Tgstation.Server.Host/Configuration/SwarmConfiguration.cs
  src/Tgstation.Server.Host/Extensions/Converters/VersionConverter.cs
  tests/Tgstation.Server.Host.Tests/Extensions/Converters/TestVersionConverter.cs
  tests/Tgstation.Server.Host.Tests/Setup/TestSetupWizard.cs
Labels: Fix, Release

#1228 Fix watchdog shutdown script invocation
  build/Version.props
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
Labels: Fix, Release

#1229 Make webpanel redirection work on presence of `Api` header
  src/Tgstation.Server.Host/Controllers/ControlPanelController.cs
  src/Tgstation.Server.Host/Controllers/HomeController.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Fix

#1230 Fix DMAPI spacing to be compliant with main
  build/Version.props
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/v3210/api.dm
  src/DMAPI/tgs/v4/api.dm
  src/DMAPI/tgs/v5/api.dm
Labels: Area: DMAPI

#1233 v4.10.1
  build/Version.props
  src/Tgstation.Server.Host/Controllers/HomeController.cs
  src/Tgstation.Server.Host/Controllers/RepositoryController.cs
Labels: Fix, Release
