Repository tgstation/tgstation-server, pull requests merged in 2022-08, with the labels that each got.

#1371 Fix bad if statement
  build/Version.props
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitHubRemoteDeploymentManager.cs
Labels: Fix, Area: Repository

#1377 Update CodeQL Workflow
  .github/workflows/codeql-analysis.yml
Labels: CI/CD, GitHub

#1376 Improves security docs
  SECURITY.md
Labels: Documentation

#1379 Add -verbose argument to Dream Daemon by default
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
Labels: Feature, Area: Watchdog, Component Issue

#1382 Fix DD response model
  build/Version.props
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
Labels: Fix, Release
