Repository tgstation/tgstation-server, pull requests merged in 2023-09, with the labels that each got.

#1647 Bump node version used to next LTS
  build/Dockerfile
Labels: CI/CD

#1646 Fixes ambiguous inheritdocs
  src/Tgstation.Server.Client/AdministrationClient.cs
  src/Tgstation.Server.Client/Components/ByondClient.cs
  src/Tgstation.Server.Client/Components/ChatBotsClient.cs
  src/Tgstation.Server.Client/Components/ConfigurationClient.cs
  src/Tgstation.Server.Client/Components/DreamMakerClient.cs
  src/Tgstation.Server.Client/Components/InstancePermissionSetClient.cs
  src/Tgstation.Server.Client/Components/JobsClient.cs
  src/Tgstation.Server.Client/InstanceManagerClient.cs
  src/Tgstation.Server.Client/UserGroupsClient.cs
  src/Tgstation.Server.Client/UsersClient.cs
  src/Tgstation.Server.Host/Components/Byond/ByondExecutableLock.cs
  src/Tgstation.Server.Host/Components/Chat/ChatManager.cs
  src/Tgstation.Server.Host/Components/InstanceManager.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  src/Tgstation.Server.Host/Core/ServerUpdater.cs
  src/Tgstation.Server.Host/IO/Console.cs
  src/Tgstation.Server.Host/Jobs/JobService.cs
  src/Tgstation.Server.Host/Models/ChatBot.cs
  src/Tgstation.Server.Host/Models/CompileJob.cs
  src/Tgstation.Server.Host/Models/DreamMakerSettings.cs
  src/Tgstation.Server.Host/Models/InstancePermissionSet.cs
  src/Tgstation.Server.Host/Models/Job.cs
  src/Tgstation.Server.Host/Models/OAuthConnection.cs
  src/Tgstation.Server.Host/Models/RepositorySettings.cs
  src/Tgstation.Server.Host/Models/RevisionInformation.cs
  src/Tgstation.Server.Host/Models/TestMerge.cs
  src/Tgstation.Server.Host/Models/User.cs
  src/Tgstation.Server.Host/Models/UserGroup.cs
  src/Tgstation.Server.Host/Security/AuthenticationContextFactory.cs
  src/Tgstation.Server.Host/Security/IdentityCache.cs
  src/Tgstation.Server.Host/Server.cs
  src/Tgstation.Server.Host/System/WindowsNetworkPromptReaper.cs
Labels: Documentation, Code Improvement, CI Cleared

#1648 Added new TGS logo
  build/logo.svg
Labels: Feature, CI Cleared

#1650 Correctly centres the new logo
  build/logo.svg
Labels: Feature, CI Cleared

#1651 New Icon integration
  .gitignore
  build/ControlPanelVersion.props
  build/NugetCommon.props
  build/Version.props
  build/package/deb/MakeInstall
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Bundle.wxs
  build/package/winget/Tgstation.Server.Host.Service.Wix/Package.wxs
  build/package/winget/Tgstation.Server.Host.Service.Wix/Tgstation.Server.Host.Service.Wix.wixproj
  build/package/winget/prepare_installer_input_artifacts.ps1
  build/tgs.ico
  build/tgs.png
  src/Tgstation.Server.Common/Tgstation.Server.Common.csproj
  src/Tgstation.Server.Common/build_logo.js
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  tgstation-server.sln
Labels: CI/CD

#1652 v5.16.0 Release
  .gitignore
  build/ControlPanelVersion.props
  build/NugetCommon.props
  build/Version.props
  build/package/deb/MakeInstall
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Bundle.wxs
  build/package/winget/Tgstation.Server.Host.Service.Wix/Package.wxs
  build/package/winget/Tgstation.Server.Host.Service.Wix/Tgstation.Server.Host.Service.Wix.wixproj
  build/package/winget/prepare_installer_input_artifacts.ps1
  build/tgs.ico
  build/tgs.png
  src/Tgstation.Server.Common/Tgstation.Server.Common.csproj
  src/Tgstation.Server.Common/build_logo.js
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  tgstation-server.sln
Labels: Release

#1653 Regenerate changelog.yml after deploying. Fix logo embedded in Windows exes
  .github/workflows/ci-pipeline.yml
  .gitignore
  build/logo.svg
  src/Tgstation.Server.Common/Tgstation.Server.Common.csproj
  src/Tgstation.Server.Common/build_logo.js
Labels: CI/CD

#1654 Switch to ForTheBadge mirror
  README.md
Labels: Documentation

#1655 Update to Wix 4.0.2
  build/package/winget/.config/dotnet-tools.json
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Tgstation.Server.Host.Service.Wix.Bundle.wixproj
  build/package/winget/Tgstation.Server.Host.Service.Wix.Extensions/Tgstation.Server.Host.Service.Wix.Extensions.csproj
  build/package/winget/Tgstation.Server.Host.Service.Wix/Tgstation.Server.Host.Service.Wix.wixproj
Labels: Windows Only, Dependencies

#1657 v5.16.1: Control panel diagnostic logging
  build/Version.props
  src/Tgstation.Server.Host/Controllers/ControlPanelController.cs
Labels: Logging, Release

#1656 General dependency updates
  build/Version.props
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tools/Tgstation.Server.ReleaseNotes/Program.cs
Labels: Dependencies
