Repository tgstation/tgstation-server, pull requests merged in 2023-08, with the labels that each got.

#1618 Fix systemd restart policy
  build/tgstation-server.service
Labels: Fix, Host Watchdog Change, Posix Only

#1619 v5.13.5 Release
  build/Version.props
Labels: Release

#1620 Dependency updates. Pin Moq
  build/ControlPanelVersion.props
  build/TestCommon.props
  build/Version.props
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tools/Tgstation.Server.ReleaseNotes/Tgstation.Server.ReleaseNotes.csproj
Labels: Dependencies

#1621 v5.13.6: Fix windows console watchdog, missing BYOND version, and configuration listing
  .github/workflows/ci-pipeline.yml
  build/Version.props
  src/Tgstation.Server.Host.Console/Program.cs
  src/Tgstation.Server.Host.Watchdog/NoopSignalChecker.cs
  src/Tgstation.Server.Host/Controllers/ConfigurationController.cs
  tests/Tgstation.Server.Host.Tests/Components/StaticFiles/TestConfiguration.cs
  tests/Tgstation.Server.Tests/Live/Instance/ByondTest.cs
Labels: Fix, Windows Only, Runner: Console

#1622 Add deployment stage awareness to Discord embeds
  build/Version.props
  src/Tgstation.Server.Api/Models/ErrorCode.cs
  src/Tgstation.Server.Host/Components/Chat/ChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/IChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/Provider.cs
  src/Tgstation.Server.Host/Components/Deployment/DmbFactory.cs
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Components/Deployment/ICompileJobSink.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/BaseRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitHubRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitLabRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/IRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/IRemoteDeploymentManagerFactory.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/NoOpRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/RemoteDeploymentManagerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
  tests/Tgstation.Server.Tests/Live/DummyChatProvider.cs
  tgstation-server.sln
Labels: Feature, Code Improvement, HTTP API, Area: Chat

#1623 Update to .NET 8 preview 7
  build/Version.props
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Models/ChatChannel.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Dependencies, .NET

#1625 v5.13.7: Fix config listing 500 error
  build/Version.props
  src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs
  src/Tgstation.Server.Host/Components/StaticFiles/IConfiguration.cs
  src/Tgstation.Server.Host/Controllers/ConfigurationController.cs
  tests/Tgstation.Server.Host.Tests/Components/StaticFiles/TestConfiguration.cs
  tests/Tgstation.Server.Tests/Live/Instance/ConfigurationTest.cs
Labels: Fix, Priority: High, Area: Static Files, Regression Test

#1627 Winget template update
  build/package/winget/manifest/Tgstation.Server.installer.yaml
  build/package/winget/manifest/Tgstation.Server.locale.en-US.yaml
  build/package/winget/manifest/Tgstation.Server.yaml
  tools/Tgstation.Server.ReleaseNotes/Program.cs
Labels: CI/CD

#1629 Deprecation notice for based meme removal
  build/Version.props
  src/Tgstation.Server.Api/Models/DiscordConnectionStringBuilder.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  tests/Tgstation.Server.Tests/Live/Instance/ChatTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/InstanceTest.cs
  tools/Tgstation.Server.Migrator.Comms/Program.cs
Labels: HTTP API

#1631 Clean up false errors with VSC GitHub Actions Extension
  .github/workflows/ci-pipeline.yml
Labels: CI/CD

#1634 Cleanup deployment conditionals
  .github/workflows/ci-pipeline.yml
Labels: Fix, CI/CD

#1632 ReleaseNotes/Changelog Overhaul + MariaDB CI Fix
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-pr-has-milestone.yml
  .github/workflows/ci-pipeline.yml
  .gitignore
  build/Version.props
  build/package/deb/build_package.sh
  build/package/deb/debian/changelog
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  src/Tgstation.Server.Common/Tgstation.Server.Common.csproj
  src/Tgstation.Server.Host/Configuration/ControlPanelConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Extensions/Converters/VersionConverter.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tools/Tgstation.Server.ReleaseNotes/Change.cs
  tools/Tgstation.Server.ReleaseNotes/Changelist.cs
  tools/Tgstation.Server.ReleaseNotes/Component.cs
  tools/Tgstation.Server.ReleaseNotes/Program.cs
  tools/Tgstation.Server.ReleaseNotes/ReleaseNotes.cs
  tools/Tgstation.Server.ReleaseNotes/Tgstation.Server.ReleaseNotes.csproj
Labels: Fix, Feature, CI/CD

#1630 Bring client version in line
  .github/workflows/ci-pipeline.yml
  build/Version.props
Labels: Client

#1636 v5.14.0 plus CI fixes
  .github/workflows/ci-pipeline.yml
  build/Common.props
  build/NugetCommon.props
  build/Version.props
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tools/Tgstation.Server.ReleaseNotes/Program.cs
Labels: Fix, CI/CD, Dependencies, Release

#1639 v5.15.0 release. Minor setup fixes
  build/ControlPanelVersion.props
  build/Version.props
  src/Tgstation.Server.Host/ServerFactory.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  tests/Tgstation.Server.Host.Tests/Setup/TestSetupWizard.cs
Labels: Fix, Dependencies, Release

#1641 Get rid of a GHA extension warning
  .github/workflows/ci-pipeline.yml
Labels: Fix, Maintainability Issue

#1642 v5.15.1. Fix winget deployments
  .github/workflows/ci-pipeline.yml
  build/Version.props
  build/package/winget/push_manifest.ps1
Labels: CI/CD, Release

#1643 v5.15.1: Fix .msi upload during deployment
  .github/workflows/ci-pipeline.yml
Labels: CI/CD, Release

#1644 v5.15.1: Fix mkdir call
  build/package/winget/push_manifest.ps1
Labels: CI/CD, Release

#1645 Fix setting `TGS_HOST_NO_WEBPANEL=true` in CI
  .github/workflows/ci-pipeline.yml
  .github/workflows/code-scanning.yml
  build/package/deb/build_package.sh
Labels: CI/CD
