Repository tgstation/tgstation-server, pull requests merged in 2023-10, with the labels that each got.

#1659 Revert "Switch to ForTheBadge mirror"
  README.md
Labels: Documentation, Revert

#1660 Fix weird log formatting in `ProcessExecutor`
  src/Tgstation.Server.Host/System/ProcessExecutor.cs
Labels: Logging

#1661 Update to .NET 8 RC1 and Update EFCore
  .github/workflows/ci-pipeline.yml
  build/Version.props
  build/analyzers.ruleset
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Dependencies

#1662 Adjust Discord embed footer when updated
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
Labels: Feature

#1664 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Documentation

#1668 v5.16.2: Fix issues with test merges being removed by auto-update
  build/Version.props
  src/Tgstation.Server.Host/Components/Instance.cs
  src/Tgstation.Server.Host/Jobs/IJobManager.cs
  src/Tgstation.Server.Host/Jobs/JobHandler.cs
  src/Tgstation.Server.Host/Jobs/JobService.cs
  src/Tgstation.Server.Host/Utils/GitHub/GitHubClientFactory.cs
  tests/Tgstation.Server.Host.Tests/Components/Chat/Providers/TestDiscordProvider.cs
  tests/Tgstation.Server.Host.Tests/Components/Chat/Providers/TestIrcProvider.cs
  tests/Tgstation.Server.Host.Tests/Jobs/TestJobHandler.cs
Labels: Fix, Logging, Component Issue, Release, Area: Instance

#1670 Pin wingetcreate due to constant issues
  .github/workflows/ci-pipeline.yml
Labels: CI/CD

#1672 Add bad BYOND build 515.1617
  .github/workflows/ci-pipeline.yml
  tests/Tgstation.Server.Tests/Live/Instance/ByondTest.cs
Labels: CI/CD

#1671 Nuget package updates
  build/ControlPanelVersion.props
  build/TestCommon.props
  build/Version.props
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Dependencies

#1673 Add another possible win32 error to dump tests
  tests/Tgstation.Server.Tests/Live/Instance/WatchdogTest.cs
Labels: CI/CD

#1679 Release ValueTask converted client package
  build/Version.props
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
Labels: Client

#1675 Regression tests and DMAPI fix
  build/Version.props
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/core/core.dm
  src/DMAPI/tgs/v5/__interop_version.dm
  src/Tgstation.Server.Host/Components/Interop/Bridge/RuntimeInformation.cs
  src/Tgstation.Server.Host/Components/Session/ReattachInformation.cs
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Models/ReattachInformationBase.cs
  src/Tgstation.Server.Host/Utils/GitHub/GitHubClientFactory.cs
  tests/DMAPI/LongRunning/Test.dm
  tests/DMAPI/LongRunning/long_running_test_rooted.dme
  tests/Tgstation.Server.Tests/Live/Instance/ConfigurationTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/InstanceTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/WatchdogTest.cs
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
  tgstation-server.sln
Labels: Fix, Area: DMAPI, Component Issue, Regression Test

#1682 Add visibility to DMAPI
  build/Version.props
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/core/core.dm
  src/DMAPI/tgs/core/datum.dm
  src/DMAPI/tgs/v5/_defines.dm
  src/DMAPI/tgs/v5/api.dm
  src/DMAPI/tgs/v5/undefs.dm
  tests/DMAPI/LongRunning/Test.dm
  tests/Tgstation.Server.Tests/Live/Instance/ConfigurationTest.cs
Labels: Feature, Area: DMAPI

#1683 v5.16.4: Fix static files not working on Linux
  .github/workflows/check-pr-has-milestone.yml
  .github/workflows/ci-pipeline.yml
  README.md
  build/Version.props
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Host/Components/Deployment/HardLinkDmbProvider.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdogFactory.cs
  tests/DMAPI/LongRunning/Test.dm
  tests/DMAPI/LongRunning/long_running_test_rooted.dme
  tests/Tgstation.Server.Tests/Live/Instance/ConfigurationTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/WatchdogTest.cs
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
Labels: Fix, Priority: CRITICAL, Area: Watchdog, Area: Compiler, Component Issue, Watchdog: Advanced, Release, Regression Test

#1688 Update Caddy Instructions
  README.md
Labels: Documentation

#1690 Fix that weirdass DMAPI bug relating to `del(world)`
  build/Version.props
  src/DMAPI/tgs.dm
  src/DMAPI/tgs/core/datum.dm
  src/DMAPI/tgs/v4/api.dm
  src/DMAPI/tgs/v5/api.dm
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  tests/DMAPI/test_setup.dm
Labels: Fix, Area: DMAPI, Area: Compiler

#1691 Minor integration test fixes
  tests/DMAPI/LongRunning/PreCompile-GenerateRandomResource.bat
  tests/DMAPI/LongRunning/PreCompile-GenerateRandomResource.sh
  tests/DMAPI/LongRunning/Test.dm
  tests/DMAPI/LongRunning/resource.txt
  tests/Tgstation.Server.Tests/Live/Instance/ConfigurationTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/WatchdogTest.cs
  tgstation-server.sln
Labels: CI/CD
