Repository tgstation/tgstation-server, pull requests merged in 2023-07, with the labels that each got.

#1579 Release v5.12.7: Fix deployments failing if creating GitHub deployments was enabled and GitHub returned bad data
  build/Version.props
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitHubRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitLabRemoteDeploymentManager.cs
Labels: Fix, Area: Compiler, Component Issue, Release

#1585 Fixes for nightly build errors
  src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdog.cs
  src/Tgstation.Server.Host/Swarm/SwarmService.cs
  tests/Tgstation.Server.Host.Tests/Swarm/TestSwarmProtocol.cs
Labels: Fix, Logging, Swarm

#1588 Setup GitHub actions for V6 branch
  .github/workflows/auto-approve-dominions-prs.yml
  .github/workflows/ci-pipeline.yml
  .github/workflows/code-scanning.yml
  .github/workflows/v6-integration.yml
Labels: CI/CD

#1593 Do not publish signed .deb unless deploying
  .github/workflows/ci-pipeline.yml
Labels: CI/CD, Posix Only

#1591 Updates docker image to debian 12
  build/Dockerfile
Labels: Docker

#1598 Fix winget package dependency
  build/package/winget/manifest/Tgstation.Server.installer.yaml
Labels: Fix, CI/CD, Windows Only, Dependencies

#1600 Elasticsearch configuration improvements. Fix System Channels. winget README update. v5.13.2 Release
  README.md
  build/Version.props
  src/Tgstation.Server.Host/Components/Chat/ChatManager.cs
  src/Tgstation.Server.Host/Configuration/ElasticsearchConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  tests/Tgstation.Server.Host.Tests/Setup/TestSetupWizard.cs
Labels: Fix, Documentation, Area: Chat, Configuration, Release

#1601 Fix Service having extraeneous dependency. v5.13.3 release
  build/Version.props
  src/Tgstation.Server.Host.Service/Program.cs
  src/Tgstation.Server.Host.Service/ServerService.cs
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
Labels: Fix, Windows Only, Release

#1602 Fix the -map-threads test
  .github/workflows/ci-pipeline.yml
  tests/Tgstation.Server.Tests/TestVersions.cs
Labels: Fix, Regression Test

#1604 Bundle MariaDB (remotely) in installer as an option
  README.md
  build/TestCommon.props
  build/Version.props
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Bundle.wxs
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Tgstation.Server.Host.Service.Wix.Bundle.wixproj
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Theme.wxl
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Theme.xml
  build/package/winget/Tgstation.Server.Host.Service.Wix/Package.wxs
  build/package/winget/prepare_installer_input_artifacts.ps1
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Configuration/InternalConfiguration.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tools/Tgstation.Server.ReleaseNotes/Tgstation.Server.ReleaseNotes.csproj
Labels: Feature, Documentation, Windows Only

#1607 Add a 1 hour test timeout to CI
  build/ci.runsettings
Labels: CI/CD

#1608 Fix service arguments during install. v5.13.4 Release
  build/Version.props
  src/Tgstation.Server.Host.Service/Program.cs
  src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs
Labels: Fix, Performance, Runner: Service

#1605 Add Windows service + SystemD to features list
  docs/Features.dox
Labels: Documentation

#1609 Prevent DumpOnHealthCheckRestart from crashing the monitor
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
Labels: Fix, Area: Watchdog

#1611 Update README.md Stopping section
  README.md
Labels: Documentation

#1610 More Windows installation UX improvements
  README.md
  build/Version.props
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Bundle.wxs
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Theme.wxl
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Theme.xml
  build/package/winget/Tgstation.Server.Host.Service.Wix.Extensions/InstallationExtensions.cs
  build/package/winget/Tgstation.Server.Host.Service.Wix/Package.wxs
  src/Tgstation.Server.Host.Common/PipeCommands.cs
  src/Tgstation.Server.Host.Service/Program.cs
  src/Tgstation.Server.Host.Service/ServerService.cs
  src/Tgstation.Server.Host.Watchdog/IWatchdog.cs
  src/Tgstation.Server.Host.Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  src/Tgstation.Server.Host/Configuration/InternalConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Core/CommandPipeManager.cs
  src/Tgstation.Server.Host/Properties/MasterVersionsAttribute.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tests/Tgstation.Server.Host.Service.Tests/TestServerService.cs
  tools/Tgstation.Server.ReleaseNotes/Tgstation.Server.ReleaseNotes.csproj
Labels: CI/CD, Windows Only, Runner: Service

#1615 Switch to using `Microsoft.Data.SqlClient`
  src/Tgstation.Server.Host/Database/DatabaseConnectionFactory.cs
  src/Tgstation.Server.Host/Database/SqlServerDatabaseContext.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tests/Tgstation.Server.Host.Tests/Database/TestDatabaseConnectionFactory.cs
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
Labels: Dependencies

#1616 Add missing BYOND zip cache to unit test jobs
  .github/workflows/ci-pipeline.yml
Labels: CI/CD, Oversight

#1614 .NET 8 Migration
  .dockerignore
  .github/CONTRIBUTING.md
  .github/workflows/ci-pipeline.yml
  .github/workflows/code-scanning.yml
  README.md
  build/Common.props
  build/Dockerfile
  build/Version.props
  build/package/deb/build_package.sh
  build/package/deb/debian/control
  build/package/winget/manifest/Tgstation.Server.installer.yaml
  src/Tgstation.Server.Client/Components/ConfigurationClient.cs
  src/Tgstation.Server.Client/ServerClientFactory.cs
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host.Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Components/Byond/ByondManager.cs
  src/Tgstation.Server.Host/Components/README.md
  src/Tgstation.Server.Host/Configuration/FileLoggingConfiguration.cs
  src/Tgstation.Server.Host/Configuration/GeneralConfiguration.cs
  src/Tgstation.Server.Host/Configuration/SecurityConfiguration.cs
  src/Tgstation.Server.Host/Database/Design/SqlServerDesignTimeDbContextFactory.cs
  src/Tgstation.Server.Host/Database/SqlServerDatabaseContext.cs
  src/Tgstation.Server.Host/IO/DefaultIOManager.cs
  src/Tgstation.Server.Host/README.md
  src/Tgstation.Server.Host/ServerFactory.cs
  src/Tgstation.Server.Host/Setup/SetupWizard.cs
  src/Tgstation.Server.Host/System/ProcessExecutor.cs
  src/Tgstation.Server.Host/System/SystemDManager.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Host/Utils/README.md
  src/Tgstation.Server.Host/appsettings.yml
  tests/Tgstation.Server.Host.Tests/Setup/TestSetupWizard.cs
  tests/Tgstation.Server.Host.Tests/Utils/TestAsyncDelayer.cs
  tools/Tgstation.Server.Migrator.Comms/Program.cs
  tools/Tgstation.Server.Migrator/Program.cs
  tools/Tgstation.Server.Migrator/Properties/RuntimeDistributableAttribute.cs
  tools/Tgstation.Server.Migrator/Tgstation.Server.Migrator.csproj
Labels: CI/CD, Documentation, Code Improvement, Dependencies, .NET
