Repository tgstation/tgstation-server, pull requests merged in 2024-07, with the labels that each got.

#1820 v6.6.1: Deployment Lock State Auditing
  build/Version.props
  src/DMAPI/tgs/v5/api.dm
  src/Tgstation.Server.Api/Models/EngineVersion.cs
  src/Tgstation.Server.Host/Components/Chat/Commands/PullRequestsCommand.cs
  src/Tgstation.Server.Host/Components/Deployment/DeploymentLockManager.cs
  src/Tgstation.Server.Host/Components/Deployment/DmbFactory.cs
  src/Tgstation.Server.Host/Components/Deployment/DmbLock.cs
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Components/Deployment/HardLinkDmbProvider.cs
  src/Tgstation.Server.Host/Components/Deployment/IDmbFactory.cs
  src/Tgstation.Server.Host/Components/Deployment/ILatestCompileJobProvider.cs
  src/Tgstation.Server.Host/Components/Engine/EngineManager.cs
  src/Tgstation.Server.Host/Components/Engine/OpenDreamInstallation.cs
  src/Tgstation.Server.Host/Components/Instance.cs
  src/Tgstation.Server.Host/Components/InstanceFactory.cs
  src/Tgstation.Server.Host/Components/InstanceWrapper.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  src/Tgstation.Server.Host/Components/Session/SessionPersistor.cs
  src/Tgstation.Server.Host/Components/Watchdog/AdvancedWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
  src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdog.cs
  src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs
  src/Tgstation.Server.Host/Extensions/TopicClientExtensions.cs
  tests/DMAPI/LongRunning/Test.dm
  tests/Tgstation.Server.Tests/Live/Instance/DeploymentTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/EngineTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/InstanceTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/JobsRequiredTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/WatchdogTest.cs
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
  tests/Tgstation.Server.Tests/Live/TestingGitHubService.cs
Labels: Refactor, Fix, Logging, Release

#1834 Create dependabot.yml for automatic Nuget update PRs
  .github/dependabot.yml
Labels: CI/CD, Dependencies

#1841 Add full size logo to readme as header
  README.md
Labels: Documentation, CI Cleared

#1835 Guard against users using relative pathing to set the project name to the .dme in the repository
  build/Version.props
  src/Tgstation.Server.Api/Models/ErrorCode.cs
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Controllers/InstanceController.cs
  src/Tgstation.Server.Host/Database/DatabaseSeeder.cs
  src/Tgstation.Server.Host/IO/DefaultIOManager.cs
  src/Tgstation.Server.Host/IO/IIOManager.cs
  src/Tgstation.Server.Host/System/IPlatformIdentifier.cs
  src/Tgstation.Server.Host/System/PlatformIdentifier.cs
  tests/Tgstation.Server.Tests/Live/Instance/DeploymentTest.cs
Labels: Client, Fix, Security, HTTP API, Area: Compiler, Swarm

#1842 v6.8.0
  .github/dependabot.yml
  .github/workflows/ci-pipeline.yml
  README.md
  build/Version.props
  build/package/winget/Tgstation.Server.Host.Service.Wix.Extensions/Tgstation.Server.Host.Service.Wix.Extensions.csproj
  src/Tgstation.Server.Api/Models/ErrorCode.cs
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Controllers/InstanceController.cs
  src/Tgstation.Server.Host/Database/DatabaseSeeder.cs
  src/Tgstation.Server.Host/IO/DefaultIOManager.cs
  src/Tgstation.Server.Host/IO/IIOManager.cs
  src/Tgstation.Server.Host/System/IPlatformIdentifier.cs
  src/Tgstation.Server.Host/System/PlatformIdentifier.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tests/Tgstation.Server.Host.Tests/Tgstation.Server.Host.Tests.csproj
  tests/Tgstation.Server.Tests/Live/Instance/DeploymentTest.cs
Labels: Release

#1843 Update SECURITY.md with better version support information
  SECURITY.md
Labels: Documentation

#1844 Re-run flaky tests up to 3 times
  .github/workflows/rerun-flaky-tests.yml
Labels: CI/CD
