Repository tgstation/tgstation-server, pull requests merged in 2024-10, with the labels that each got.

#1946 Gorillionth CI Fix
  .github/workflows/ci-security.yml
  .github/workflows/new-pr-comments.yml
  src/Tgstation.Server.Host/Core/Application.cs
  tests/Tgstation.Server.Tests/Live/HoldLastObserver.cs
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
  tests/Tgstation.Server.Tests/Live/UsersTest.cs
Labels: CI/CD, size/L

#1935 Refactor IrcProvider just a little
  README.md
  build/Version.props
  src/Tgstation.Server.Api/Models/IrcConnectionStringBuilder.cs
  src/Tgstation.Server.Api/Models/IrcPasswordType.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/ProviderFactory.cs
  src/Tgstation.Server.Host/Configuration/FileLoggingConfiguration.cs
  tests/Tgstation.Server.Host.Tests/Components/Chat/Providers/TestIrcProvider.cs
Labels: Refactor, Feature, Area: Chat, CI Cleared, size/L

#1954 Initial GraphQL API release. Also releasing REST API v10.10
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-pipeline.yml
  build/Version.props
  src/README.md
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client.GraphQL/GQL/Queries/OAuthInformation.graphql
  src/Tgstation.Server.Client.GraphQL/GQL/Queries/UnauthenticatedServerInformation.graphql
  src/Tgstation.Server.Client.GraphQL/Tgstation.Server.Client.GraphQL.csproj
  src/Tgstation.Server.Host/Authority/IUserAuthority.cs
  src/Tgstation.Server.Host/Authority/UserAuthority.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/GraphQL/Interceptors/RightsTypeInterceptor.cs
  src/Tgstation.Server.Host/GraphQL/Mutation.cs
  src/Tgstation.Server.Host/GraphQL/Mutations/Payloads/LoginPayload.cs
  src/Tgstation.Server.Host/GraphQL/Mutations/UserGroupMutations.cs
  src/Tgstation.Server.Host/GraphQL/Mutations/UserMutations.cs
  src/Tgstation.Server.Host/GraphQL/Query.cs
  src/Tgstation.Server.Host/GraphQL/Scalars/JwtType.cs
  src/Tgstation.Server.Host/GraphQL/Scalars/SemverType.cs
  src/Tgstation.Server.Host/GraphQL/Subscription.cs
  src/Tgstation.Server.Host/GraphQL/Subscriptions/UserSubscriptions.cs
  src/Tgstation.Server.Host/GraphQL/Types/GatewayInformation.cs
  src/Tgstation.Server.Host/GraphQL/Types/OAuth/BasicOAuthProviderInfo.cs
  src/Tgstation.Server.Host/GraphQL/Types/OAuth/FullOAuthProviderInfo.cs
  src/Tgstation.Server.Host/GraphQL/Types/OAuth/OAuthConnection.cs
  src/Tgstation.Server.Host/GraphQL/Types/OAuth/OAuthProviderInfos.cs
  src/Tgstation.Server.Host/GraphQL/Types/OAuth/RedirectOAuthProviderInfo.cs
  src/Tgstation.Server.Host/GraphQL/Types/OAuth/ServerUrlOAuthProviderInfo.cs
  src/Tgstation.Server.Host/GraphQL/Types/User.cs
  src/Tgstation.Server.Host/Properties/MasterVersionsAttribute.cs
  src/Tgstation.Server.Host/README.md
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Host/appsettings.yml
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
  tests/Tgstation.Server.Tests/TestVersions.cs
  tools/Tgstation.Server.ReleaseNotes/Component.cs
  tools/Tgstation.Server.ReleaseNotes/Program.cs
Labels: Fix, CI/CD, Documentation, REST, size/L, GraphQL

#1955 More GraphQL stuff + Webpanel version bump
  .github/workflows/ci-pipeline.yml
  build/Version.props
  build/WebpanelVersion.props
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Client.GraphQL/AuthenticatedGraphQLServerClient.cs
  src/Tgstation.Server.Client.GraphQL/GQL/Mutations/Login.graphql
  src/Tgstation.Server.Client.GraphQL/LoginResultExtensions.cs
  src/Tgstation.Server.Host/Authority/ILoginAuthority.cs
  src/Tgstation.Server.Host/Authority/LoginAuthority.cs
  src/Tgstation.Server.Host/Controllers/ApiRootController.cs
  src/Tgstation.Server.Host/Extensions/ApplicationBuilderExtensions.cs
  src/Tgstation.Server.Host/GraphQL/Mutation.cs
  src/Tgstation.Server.Host/GraphQL/Mutations/Payloads/LoginResult.cs
  tests/Tgstation.Server.Tests/Live/RawRequestTests.cs
Labels: Fix, Dependencies, size/M, GraphQL

#1958 Update Wix to 5.0.2
  build/package/winget/.config/dotnet-tools.json
  build/package/winget/Tgstation.Server.Host.Service.Wix.Bundle/Tgstation.Server.Host.Service.Wix.Bundle.wixproj
  build/package/winget/Tgstation.Server.Host.Service.Wix.Extensions/Tgstation.Server.Host.Service.Wix.Extensions.csproj
  build/package/winget/Tgstation.Server.Host.Service.Wix/Tgstation.Server.Host.Service.Wix.wixproj
Labels: Dependencies, size/S

#1959 Dependencies Updates
  build/WebpanelVersion.props
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Shared/Tgstation.Server.Shared.csproj
Labels: Dependencies, size/M

#1967 HotChocolate Update
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Dependencies, size/S

#1973 Ubuntu 24 becoming latest fixes
  .github/workflows/ci-pipeline.yml
  build/package/deb/appsettings.GitHub.yml
  build/package/winget/appsettings.GitHub.yml
  tgstation-server.sln
Labels: CI/CD, size/M

#1971 Reduce periodic deployment lock states report log level to trace
  src/Tgstation.Server.Host/Components/Deployment/DmbFactory.cs
Labels: Logging, size/XS

#1980 Hot Chocolate Update to 14.0.0-rc.3.4
  .github/dependabot.yml
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Dependencies, size/S

#1983 Update Swashbuckle to 6.9.0
  .github/dependabot.yml
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
Labels: Dependencies, size/XS

#1988 Hopefully fixes bot comments not choosing minor/patch correctly
  .github/workflows/new-pr-comments.yml
Labels: CI/CD, size/XS

#1990 Make forceFresh argument in UpdateInformation optional
  build/Version.props
  src/Tgstation.Server.Host/GraphQL/Types/UpdateInformation.cs
Labels: size/S, GraphQL

#1993 v6.11.2: Additional logging surrounding config file writes
  build/Version.props
  src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs
  src/Tgstation.Server.Host/IO/SynchronousIOManager.cs
  tests/Tgstation.Server.Host.Tests/Components/StaticFiles/TestConfiguration.cs
Labels: Logging, Release, size/M

#1995 v6.11.4: Various fixes in the static files component
  build/Version.props
  src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs
Labels: Fix, Area: Static Files, size/M
