Repository tgstation/tgstation-server, pull requests merged in 2025-01, with the labels that each got.

#2063 Add final 515 version to DMAPI tests
  .github/workflows/ci-pipeline.yml
Labels: CI/CD, size/XS

#2065 [s] v6.12.3: Why are we still here? Just to suffer??
  build/Version.props
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Security/TgsAuthorizeAttribute.cs
  src/Tgstation.Server.Host/Security/TgsGraphQLAuthorizeAttribute.cs
  tests/Tgstation.Server.Tests/Live/Instance/InstanceTest.cs
  tests/Tgstation.Server.Tests/Live/Instance/RepositoryTest.cs
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
Labels: Fix, Priority: CRITICAL, Security, Release, Regression Test, size/M

#2066 Hopefully fix the nix SHA update bypass thingy
  .github/workflows/ci-pipeline.yml
Labels: CI/CD, size/XS

#2086 Bump .NET version for OpenDream
  .github/workflows/ci-pipeline.yml
Labels: CI/CD, size/XS

#2096 Fix fork PR comment
  .github/workflows/new-pr-comments.yml
Labels: CI/CD, size/XS

#2095 Nix Updates
  build/package/nix/tgstation-server.nix
Labels: CI/CD, CI Cleared, size/S
