Repository tgstation/tgstation-server, pull requests merged in 2025-02, with the labels that each got.

#2087 document updates
  build/Version.props
  build/stylecop.json
  src/Tgstation.Server.Api/Models/ChatChannel.cs
  src/Tgstation.Server.Api/Models/EngineVersion.cs
  src/Tgstation.Server.Api/Models/EntityId.cs
  src/Tgstation.Server.Api/Models/Internal/ChatBotSettings.cs
  src/Tgstation.Server.Api/Models/Internal/ChatChannelBase.cs
  src/Tgstation.Server.Api/Models/Internal/CompileJob.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonApiBase.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonLaunchParameters.cs
  src/Tgstation.Server.Api/Models/Internal/Job.cs
  src/Tgstation.Server.Api/Models/Internal/ServerInformationBase.cs
  src/Tgstation.Server.Api/Models/Internal/SwarmServer.cs
  src/Tgstation.Server.Api/Models/Internal/SwarmServerInformation.cs
  src/Tgstation.Server.Api/Models/Internal/TestMergeApiBase.cs
  src/Tgstation.Server.Api/Models/Internal/TestMergeModelBase.cs
  src/Tgstation.Server.Api/Models/Internal/UpdateInformation.cs
  src/Tgstation.Server.Api/Models/NamedEntity.cs
  src/Tgstation.Server.Api/Models/Request/ServerUpdateRequest.cs
  src/Tgstation.Server.Api/Models/Response/AdministrationResponse.cs
  src/Tgstation.Server.Api/Models/Response/DreamDaemonResponse.cs
  src/Tgstation.Server.Api/Models/Response/ErrorMessageResponse.cs
  src/Tgstation.Server.Api/Models/Response/JobResponse.cs
  src/Tgstation.Server.Api/Models/Response/LogFileResponse.cs
  src/Tgstation.Server.Api/Models/Response/PaginatedResponse.cs
  src/Tgstation.Server.Api/Models/Response/ServerInformationResponse.cs
  src/Tgstation.Server.Api/Models/Response/ServerUpdateResponse.cs
  src/Tgstation.Server.Api/Models/Response/TokenResponse.cs
  src/Tgstation.Server.Api/Models/TestMergeParameters.cs
  src/Tgstation.Server.Api/Models/UserName.cs
  src/Tgstation.Server.Host/Utils/SwaggerConfiguration.cs
Labels: Documentation, REST, CI Cleared, size/M

#2105 Pre-Launch DD Event + Exception Propagation Fix
  build/TestCommon.props
  build/Version.props
  build/package/nix/tgstation-server.nix
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client.GraphQL/Tgstation.Server.Client.GraphQL.csproj
  src/Tgstation.Server.Host.Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Components/Events/EventType.cs
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Extensions/WebHostBuilderExtensions.cs
  src/Tgstation.Server.Host/GraphQL/ErrorMessageFilter.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tests/Tgstation.Server.Host.Tests/Core/TestApplication.cs
Labels: Fix, Feature, Logging, Host Watchdog Change, Dependencies, size/L

#2107 v6.13.0
  build/TestCommon.props
  build/Version.props
  build/package/nix/tgstation-server.nix
  build/stylecop.json
  src/DMAPI/tgs.dm
  src/Tgstation.Server.Api/ApiHeaders.cs
  src/Tgstation.Server.Api/Models/ChatChannel.cs
  src/Tgstation.Server.Api/Models/EngineVersion.cs
  src/Tgstation.Server.Api/Models/EntityId.cs
  src/Tgstation.Server.Api/Models/Internal/ChatBotSettings.cs
  src/Tgstation.Server.Api/Models/Internal/ChatChannelBase.cs
  src/Tgstation.Server.Api/Models/Internal/CompileJob.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonApiBase.cs
  src/Tgstation.Server.Api/Models/Internal/DreamDaemonLaunchParameters.cs
  src/Tgstation.Server.Api/Models/Internal/Job.cs
  src/Tgstation.Server.Api/Models/Internal/ServerInformationBase.cs
  src/Tgstation.Server.Api/Models/Internal/SwarmServer.cs
  src/Tgstation.Server.Api/Models/Internal/SwarmServerInformation.cs
  src/Tgstation.Server.Api/Models/Internal/TestMergeApiBase.cs
  src/Tgstation.Server.Api/Models/Internal/TestMergeModelBase.cs
  src/Tgstation.Server.Api/Models/Internal/UpdateInformation.cs
  src/Tgstation.Server.Api/Models/NamedEntity.cs
  src/Tgstation.Server.Api/Models/Request/ServerUpdateRequest.cs
  src/Tgstation.Server.Api/Models/Response/AdministrationResponse.cs
  src/Tgstation.Server.Api/Models/Response/DreamDaemonResponse.cs
  src/Tgstation.Server.Api/Models/Response/ErrorMessageResponse.cs
  src/Tgstation.Server.Api/Models/Response/JobResponse.cs
  src/Tgstation.Server.Api/Models/Response/LogFileResponse.cs
  src/Tgstation.Server.Api/Models/Response/PaginatedResponse.cs
  src/Tgstation.Server.Api/Models/Response/ServerInformationResponse.cs
  src/Tgstation.Server.Api/Models/Response/ServerUpdateResponse.cs
  src/Tgstation.Server.Api/Models/Response/TokenResponse.cs
  src/Tgstation.Server.Api/Models/TestMergeParameters.cs
  src/Tgstation.Server.Api/Models/UserName.cs
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client.GraphQL/Tgstation.Server.Client.GraphQL.csproj
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Watchdog/Watchdog.cs
  src/Tgstation.Server.Host/Components/Events/EventType.cs
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Extensions/WebHostBuilderExtensions.cs
  src/Tgstation.Server.Host/GraphQL/ErrorMessageFilter.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Host/Utils/SwaggerConfiguration.cs
  src/Tgstation.Server.Shared/Tgstation.Server.Shared.csproj
  tests/Tgstation.Server.Api.Tests/Tgstation.Server.Api.Tests.csproj
  tests/Tgstation.Server.Client.Tests/Tgstation.Server.Client.Tests.csproj
  tests/Tgstation.Server.Host.Tests/Core/TestApplication.cs
  tests/Tgstation.Server.Tests/Tgstation.Server.Tests.csproj
Labels: Release, size/L

#2108 v6.13.0 (fr this time): Version Bump + Custom Event completion event failure fix
  build/Version.props
  src/Tgstation.Server.Host/Components/Interop/Bridge/BridgeParameters.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
Labels: Fix, Release, size/S

#2109 Fix sha256 of nix serverconsole fixed deviation
  build/package/nix/ServerConsole.sha256
Labels: CI Cleared, size/XS

#2133 Add metrics and Prometheus
  README.md
  build/Dockerfile
  build/TestCommon.props
  build/Version.props
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client.GraphQL/Tgstation.Server.Client.GraphQL.csproj
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Components/InstanceFactory.cs
  src/Tgstation.Server.Host/Components/InstanceManager.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/AdvancedWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/IWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/IWatchdogFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdogFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdogFactory.cs
  src/Tgstation.Server.Host/Configuration/GeneralConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Jobs/JobService.cs
  src/Tgstation.Server.Host/System/IProcessBase.cs
  src/Tgstation.Server.Host/System/Process.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Host/Utils/GitHub/GitHubClientFactory.cs
  src/Tgstation.Server.Host/appsettings.yml
  src/Tgstation.Server.Shared/Tgstation.Server.Shared.csproj
  tests/Tgstation.Server.Client.Tests/Tgstation.Server.Client.Tests.csproj
  tests/Tgstation.Server.Host.Tests/BasicHttpMessageHandlerFactory.cs
  tests/Tgstation.Server.Host.Tests/Tgstation.Server.Host.Tests.csproj
  tests/Tgstation.Server.Host.Tests/Utils/GitHub/TestGitHubClientFactory.cs
  tests/Tgstation.Server.Tests/Live/LiveTestingServer.cs
  tests/Tgstation.Server.Tests/Live/RawRequestTests.cs
  tests/Tgstation.Server.Tests/Live/TestingGitHubService.cs
  tests/Tgstation.Server.Tests/Tgstation.Server.Tests.csproj
Labels: Feature, Documentation, Logging, Configuration, Docker, size/L

#2132 TM commits no longer reference PRs
  src/Tgstation.Server.Host/Components/Repository/Repository.cs
Labels: Area: Repository, CI Cleared, size/XS

#2136 Fix IRC throwing errors for non-GitHub update messages
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  tests/Tgstation.Server.Tests/Live/DummyChatProvider.cs
Labels: Fix, Area: Chat, size/XS

#2137 v6.14.0
  README.md
  build/Dockerfile
  build/TestCommon.props
  build/Version.props
  src/Tgstation.Server.Api/Tgstation.Server.Api.csproj
  src/Tgstation.Server.Client.GraphQL/Tgstation.Server.Client.GraphQL.csproj
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Components/InstanceFactory.cs
  src/Tgstation.Server.Host/Components/InstanceManager.cs
  src/Tgstation.Server.Host/Components/Repository/Repository.cs
  src/Tgstation.Server.Host/Components/Session/SessionController.cs
  src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/AdvancedWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/IWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/IWatchdogFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdogFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs
  src/Tgstation.Server.Host/Components/Watchdog/WatchdogFactory.cs
  src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdog.cs
  src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdogFactory.cs
  src/Tgstation.Server.Host/Configuration/GeneralConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Jobs/JobService.cs
  src/Tgstation.Server.Host/System/IProcessBase.cs
  src/Tgstation.Server.Host/System/Process.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Host/Utils/GitHub/GitHubClientFactory.cs
  src/Tgstation.Server.Host/appsettings.yml
  src/Tgstation.Server.Shared/Tgstation.Server.Shared.csproj
  tests/Tgstation.Server.Client.Tests/Tgstation.Server.Client.Tests.csproj
  tests/Tgstation.Server.Host.Tests/BasicHttpMessageHandlerFactory.cs
  tests/Tgstation.Server.Host.Tests/Tgstation.Server.Host.Tests.csproj
  tests/Tgstation.Server.Host.Tests/Utils/GitHub/TestGitHubClientFactory.cs
  tests/Tgstation.Server.Tests/Live/LiveTestingServer.cs
  tests/Tgstation.Server.Tests/Live/RawRequestTests.cs
  tests/Tgstation.Server.Tests/Live/TestingGitHubService.cs
  tests/Tgstation.Server.Tests/Tgstation.Server.Tests.csproj
Labels: Release, size/L

#2139 v6.14.1: Fix Docker health checks and app token expiry
  .github/workflows/ci-pipeline.yml
  build/Dockerfile
  build/Version.props
  src/Tgstation.Server.Host/Utils/GitHub/GitHubClientFactory.cs
Labels: Fix, Release, size/M
