Repository tgstation/tgstation-server, pull requests merged in 2025-03, with the labels that each got.

#2134 Chatbots now mention the changes to TMs in deployment messages
  src/Tgstation.Server.Host/Components/Chat/ChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/IChatManager.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs
  src/Tgstation.Server.Host/Components/Chat/Providers/Provider.cs
  src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/BaseRemoteDeploymentManager.cs
  tests/Tgstation.Server.Tests/Live/DummyChatProvider.cs
Labels: Feature, Area: Chat, Area: Compiler, CI Cleared, size/L

#2131 TM Comment Consolidation in Github/Gitlab
  .gitignore
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/.graphqlrc.json
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GQL/Mutations/CreateNote.graphql
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GQL/Mutations/ModifyNote.graphql
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GQL/Queries/GetCurrentUser.graphql
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GQL/Queries/GetMergeRequest.graphql
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GQL/Queries/GetMergeRequestNotes.graphql
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GQL/Queries/GetMergeRequests.graphql
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GraphQLGitLabClient.cs
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GraphQLGitLabClientFactory.cs
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/IGraphQLGitLabClient.cs
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/Tgstation.Server.Host.Utils.GitLab.GraphQL.csproj
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/package.json
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/yarn.lock
  src/Tgstation.Server.Host/Components/Deployment/Remote/BaseRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitHubRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/GitLabRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Deployment/Remote/NoOpRemoteDeploymentManager.cs
  src/Tgstation.Server.Host/Components/Repository/GitLabRemoteFeatures.cs
  src/Tgstation.Server.Host/Controllers/RepositoryController.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Host/Utils/GitHub/GitHubService.cs
  src/Tgstation.Server.Host/Utils/GitHub/IAuthenticatedGitHubService.cs
  tests/Tgstation.Server.Tests/Live/TestingGitHubService.cs
  tgstation-server.sln
Labels: Feature, Area: Compiler, Dependencies, CI Cleared, size/XXL

#2161 Fixes and Patch Tuesday Updates
  .github/workflows/ci-pipeline.yml
  .gitignore
  src/Tgstation.Server.Client.GraphQL/Tgstation.Server.Client.GraphQL.csproj
  src/Tgstation.Server.Client/Tgstation.Server.Client.csproj
  src/Tgstation.Server.Host.Console/Tgstation.Server.Host.Console.csproj
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/.yarnrc.yml
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/Tgstation.Server.Host.Utils.GitLab.GraphQL.csproj
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/package.json
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/yarn.lock
  src/Tgstation.Server.Host.Watchdog/Tgstation.Server.Host.Watchdog.csproj
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  src/Tgstation.Server.Shared/Tgstation.Server.Shared.csproj
  tests/Tgstation.Server.Client.Tests/Tgstation.Server.Client.Tests.csproj
  tests/Tgstation.Server.Tests/Tgstation.Server.Tests.csproj
Labels: Dependencies, size/XXL

#2059 Update to EFCore 9
  build/Version.props
  src/Tgstation.Server.Host.Utils.GitLab.GraphQL/package.json
  src/Tgstation.Server.Host/.config/dotnet-tools.json
  src/Tgstation.Server.Host/Database/Design/MySqlDesignTimeDbContextFactory.cs
  src/Tgstation.Server.Host/Database/MySqlDatabaseContext.cs
  src/Tgstation.Server.Host/Database/PostgresSqlDatabaseContext.cs
  src/Tgstation.Server.Host/Database/SqlServerDatabaseContext.cs
  src/Tgstation.Server.Host/Database/SqliteDatabaseContext.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tests/Tgstation.Server.Host.Tests/Tgstation.Server.Host.Tests.csproj
  tests/Tgstation.Server.Tests/Live/TestLiveServer.cs
Labels: Dependencies, size/M

#2165 Correct OIDC configuration documentation
  README.md
Labels: Documentation, size/XS

#2169 v6.15.1: Fixes and shit
  README.md
  build/Version.props
  build/WebpanelVersion.props
  src/Tgstation.Server.Host.Service/Tgstation.Server.Host.Service.csproj
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Tgstation.Server.Host.csproj
  tools/Tgstation.Server.ReleaseNotes/Changelist.cs
  tools/Tgstation.Server.ReleaseNotes/ChangelistEqualityComparer.cs
Labels: Fix, Documentation, size/M

#2174 v6.15.2: Fix `X-Forwarded-*` headers again
  build/Version.props
  src/Tgstation.Server.Host/Authority/UserAuthority.cs
  src/Tgstation.Server.Host/Core/Application.cs
Labels: Fix, Release, size/S

#2177 OIDC QoL
  README.md
  build/Version.props
  build/WebpanelVersion.props
  src/Tgstation.Server.Host/Configuration/OidcConfiguration.cs
  src/Tgstation.Server.Host/Core/Application.cs
  src/Tgstation.Server.Host/Security/AuthenticationContextFactory.cs
  src/Tgstation.Server.Host/Security/ITokenValidator.cs
  src/Tgstation.Server.Host/appsettings.yml
Labels: Feature, Documentation, Configuration, size/M

#2182 Critical README fix
  README.md
  tools/Tgstation.Server.ReleaseNotes/Program.cs
Labels: Documentation, size/XS
